### PR TITLE
disable email notifications

### PR DESCRIPTION
**Pull request by thisguycodes**
if I want notifications I'll set up something better later (slack?)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/conslo/webLinks/pull/3" target="_blank">ReviewNinja

**Comment by conslo** [comment]
:+1:

**Comment by conslo** [comment]
:+1:

**Comment by conslo** [comment]
image
:) :+1:

**Comment by thisguycodes** [comment]
image
:)

**Comment by thisguycodes** [comment]
:+1:

**Pull request merged**
